#!/usr/bin/env python3
"""Embed the plates' script in the captive portal as firmware/src/ff_portal_font.h.

The portal's "Featherframe" wordmark is set in the same script as the plates
(Pinyon Script, OFL, bundled with the server). The @font-face rule carrying it is
generated here — a WOFF subset of just the wordmark's glyphs, base64 as a
data URI (the portal has no internet, so the face must travel with the page)
— into a committed header. main.cpp includes it when present
(`__has_include`) and otherwise falls back to Georgia italic.

Run before `pio run` after changing the script:

    server/.venv/bin/python firmware/tools/portal_font.py

Needs fontTools in the server venv (`server/.venv/bin/pip install fonttools`).
"""
from __future__ import annotations

import base64
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(REPO, "server"))

from featherframe.render import typography  # noqa: E402

OUT_H = os.path.join(REPO, "firmware", "src", "ff_portal_font.h")
WORDMARK = "Featherframe"


def main() -> None:
    if not typography.has_script_font():
        sys.exit("the bundled script font is missing; nothing to embed")
    from fontTools import subset
    from fontTools.ttLib import TTFont

    src = typography.script_font_path()
    font = TTFont(str(src))
    opts = subset.Options()
    opts.flavor = "woff"
    opts.layout_features = ["kern", "liga", "calt"]
    opts.name_IDs = []          # drop the name table's text: the family is named by CSS
    opts.notdef_outline = False
    sub = subset.Subsetter(opts)
    sub.populate(text=WORDMARK)
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff"
    font.save(buf)
    woff = buf.getvalue()
    b64 = base64.b64encode(woff).decode("ascii")
    css = ("@font-face{font-family:'FFScript';src:url(data:font/woff;base64,"
           + b64 + ") format('woff');font-style:italic;font-weight:400 700}")
    body = (
        "// GENERATED by firmware/tools/portal_font.py — do not edit; re-run after a font change.\n"
        f"// {len(woff)} byte WOFF subset ({WORDMARK!r}) of {os.path.basename(str(src))} (OFL).\n"
        "#pragma once\n"
        f'#define FF_PORTAL_FONT_FACE "{css}"\n'
    )
    with open(OUT_H, "w") as fh:
        fh.write(body)
    print(f"wrote {OUT_H} ({len(woff)} byte WOFF, {len(css)} chars of CSS)")


if __name__ == "__main__":
    main()
